# Generated by Buildr 1.4.9, change to your liking

# Version number for this release
VERSION_NUMBER = "0.1.0"
# Group identifier for your projects
GROUP = "javaSudoku2"
COPYRIGHT = ""

defLayout = Layout.new
defLayout[:source, :main, :java] = 'src'
defLayout[:source, :test, :java] = 'tests'
defLayout[:target] = 'classes'
defLayout[:target, :main, :classes] = 'classes/main'
defLayout[:target, :test, :classes] = 'classes/test'

# Specify Maven 2.0 remote repositories here, like this:
repositories.remote << "http://repo1.maven.org/maven2"

desc "The Javasudoku2 project"
define "javaSudoku2", :layout=>defLayout do
  project.version = VERSION_NUMBER
  project.group = GROUP
  manifest["Implementation-Vendor"] = COPYRIGHT
end
